CREATE OR REPLACE VIEW nsi_export_view AS
SELECT
    geom,
    guid,
    cbfips,
    struct_typ,
    occtype AS occ_type,
    val_struct AS appr_bldg,
    sqft AS sq_foot,
    dwell_unit,
    LEAST(no_stories, 999) AS no_stories,
    val_cont AS cont_val,
    str_typ2,
    efacility,
    parid,
    parid_card,
    LEAST(year_built, 9999) AS year_built,
    a_stories,
    b_stories,
    bsmt_type,
    gsq_foot,
    occ_detail,
    major_occ,
    broad_occ,
    repl_cst,
    str_cst,
    nstra_cst,
    nstrd_cst,
    dgn_lvl,
    occ_typ2,
    tract_id,
    ffe_elev,
    g_elev,
    appr_land,
    appr_tot,
    archetype,
    arch_flood,
    arch_wind,
    arch_sw
FROM nsi;