name: Approval App Docker Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  MAIN_REPO: IN-CORE/dev-scripts
  NCSAHUB: hub.ncsa.illinois.edu/incore
  PLATFORM: "linux/amd64"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Version and Tags
        run: |
          if [ "${{ github.event.release.target_commitish }}" != "" ]; then
            BRANCH="${{ github.event.release.target_commitish }}"
          elif [[ $GITHUB_REF =~ pull ]]; then
            BRANCH="$(echo $GITHUB_REF | sed 's#refs/pull/\([0-9]*\)/merge#PR-\1#')"
          else
            BRANCH=${GITHUB_REF##*/}
          fi

          OWNER=${{ github.repository_owner }}
          OWNER_LC=${OWNER,,}

          if [ "$BRANCH" == "main" ]; then
            VERSION="$(awk '/^# \[/ { print $2; exit }' CHANGELOG.md | sed -e 's/\[//' -e 's/\]//')"
            tags="latest"
            tmpversion="${VERSION}"
            while [ "${tmpversion}" != "" ]; do
              tags="${tags} ${tmpversion}"
              tmpversion=${tmpversion%.*}
            done
          else
            VERSION="$BRANCH"
            tags="$BRANCH"
          fi

          IMAGE="approval-app"
          IMAGES=""
          for tag in ${tags}; do
            IMAGES="${IMAGES}${{ env.NCSAHUB }}/${IMAGE}:${tag},"
          done
          IMAGES="${IMAGES%,}"

          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "IMAGES=${IMAGES}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to NCSA Hub
        uses: docker/login-action@v2
        with:
          registry: hub.ncsa.illinois.edu
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ env.PLATFORM }}
          context: .
          file: keycloak/approval-flask-app/Dockerfile
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ env.IMAGES }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
            VERSION=${{ env.VERSION }}
            BUILDNUMBER=${{ github.run_number }}
            GITSHA1=${{ github.sha }}
